### ISSUE TITLE
Support for other date formats

### ISSUE THREAD

**Issue by JoannaDJ** [CherryFramework/tm-timeline#4]
Hello, is it possible to modify the javascript to add support for this date format:
(Month Year) for ex.: August 2010?

**Comment by cheh** [comment]
Hi, @JoannaDJ.

You may add custom date format using filter `tm_timeline_shortcode_supported_date_formats` - https://github.com/CherryFramework/tm-timeline/blob/master/classes/class-tm-timeline.php#L205
